//! Demiurge design-conformance tool.
//!
//! `gen` regenerates every artifact derived from the canonical inputs, and
//! `lint` enforces the spec/code/test traceability join.
//!
//! ```text
//! design/demiurge.params.toml -> crates/demiurge-cost/src/generated_params.rs
//!                             -> spec/generated/params_table.tex
//! design/requirements.toml    -> spec/generated/conformance_matrix.tex
//! ```
//!
//! Both commands are pure functions of the repository on disk, so CI can run
//! `gen` and fail on any diff (drift), then run `lint` (traceability).

use std::collections::BTreeSet;
use std::error::Error;
use std::fs;
use std::path::{Path, PathBuf};
use std::process::exit;

use regex::Regex;
use serde::Deserialize;

const PARAMS: &str = "design/demiurge.params.toml";
const REQS: &str = "design/requirements.toml";
const RS_OUT: &str = "crates/demiurge-cost/src/generated_params.rs";
const PARAMS_TEX: &str = "spec/generated/params_table.tex";
const MATRIX_TEX: &str = "spec/generated/conformance_matrix.tex";

const SCAN_RS_DIRS: &[&str] = &["crates", "xtask"];
const SCAN_TEX_DIRS: &[&str] = &["spec"];

#[derive(Debug, Deserialize)]
struct Requirements {
    #[serde(default)]
    requirement: Vec<Requirement>,
}

#[derive(Debug, Deserialize)]
struct Requirement {
    id: String,
    kind: String,
    section: String,
    #[allow(dead_code)]
    summary: String,
    #[serde(default)]
    requires_test: bool,
}

fn main() {
    let cmd = std::env::args().nth(1).unwrap_or_default();
    let res = match cmd.as_str() {
        "gen" => gen(),
        "lint" => lint(),
        other => {
            eprintln!("xtask: unknown subcommand {other:?}; expected `gen` or `lint`");
            exit(2);
        }
    };
    if let Err(e) = res {
        eprintln!("xtask {cmd}: {e}");
        exit(1);
    }
}

fn tex_escape(s: &str) -> String {
    s.replace('\\', "\\textbackslash{}")
        .replace('_', "\\_")
        .replace('%', "\\%")
        .replace('&', "\\&")
        .replace('#', "\\#")
}

fn write_if_changed(path: &str, contents: &str) -> Result<(), Box<dyn Error>> {
    let p = Path::new(path);
    if let Some(parent) = p.parent() {
        fs::create_dir_all(parent)?;
    }
    let prev = fs::read_to_string(p).unwrap_or_default();
    if prev != contents {
        fs::write(p, contents)?;
    }
    Ok(())
}

fn gen() -> Result<(), Box<dyn Error>> {
    // ---- parameters -> Rust constants + LaTeX table ----
    let table: toml::Table = toml::from_str(&fs::read_to_string(PARAMS)?)?;

    let mut consts: Vec<(String, String)> = Vec::new(); // (NAME, "ty = lit")
    let mut tex_rows: Vec<(String, String, String)> = Vec::new(); // (group, key, display)
    for (group, gval) in table.iter() {
        let Some(t) = gval.as_table() else { continue };
        for (key, v) in t.iter() {
            let name = format!("{}_{}", group.to_uppercase(), key.to_uppercase());
            let (ty, lit, disp) = match v {
                toml::Value::Integer(i) => ("u64", i.to_string(), i.to_string()),
                toml::Value::Float(f) => {
                    let mut s = format!("{f}");
                    if !s.contains('.') && !s.contains('e') {
                        s.push_str(".0");
                    }
                    ("f64", s.clone(), s)
                }
                toml::Value::Boolean(b) => ("bool", b.to_string(), b.to_string()),
                _ => continue,
            };
            consts.push((name, format!("{ty} = {lit}")));
            tex_rows.push((group.clone(), key.clone(), disp));
        }
    }
    consts.sort();
    tex_rows.sort();

    let mut rs = String::new();
    rs.push_str(
        "// @generated by `cargo xtask gen` from design/demiurge.params.toml. DO NOT EDIT.\n",
    );
    rs.push_str("#![allow(dead_code)]\n\n");
    for (name, tylit) in &consts {
        rs.push_str(&format!("pub const {name}: {tylit};\n"));
    }
    write_if_changed(RS_OUT, &rs)?;

    let mut pt = String::new();
    pt.push_str(
        "% @generated by `cargo xtask gen` from design/demiurge.params.toml. DO NOT EDIT.\n",
    );
    pt.push_str("\\begin{tabular}{lll}\n\\toprule\nGroup & Parameter & Value \\\\\n\\midrule\n");
    for (g, k, d) in &tex_rows {
        pt.push_str(&format!(
            "{} & {} & {} \\\\\n",
            tex_escape(g),
            tex_escape(k),
            tex_escape(d)
        ));
    }
    pt.push_str("\\bottomrule\n\\end{tabular}\n");
    write_if_changed(PARAMS_TEX, &pt)?;

    // ---- requirements -> conformance matrix ----
    let reqs: Requirements = toml::from_str(&fs::read_to_string(REQS)?)?;
    let mut rows = reqs.requirement;
    rows.sort_by(|a, b| a.id.cmp(&b.id));

    let mut cm = String::new();
    cm.push_str("% @generated by `cargo xtask gen` from design/requirements.toml. DO NOT EDIT.\n");
    cm.push_str(
        "\\begin{tabular}{llll}\n\\toprule\nRequirement & Kind & Spec \\S & Test \\\\\n\\midrule\n",
    );
    for r in &rows {
        cm.push_str(&format!(
            "{} & {} & {} & {} \\\\\n",
            tex_escape(&r.id),
            tex_escape(&r.kind),
            tex_escape(&r.section),
            if r.requires_test { "yes" } else { "--" }
        ));
    }
    cm.push_str("\\bottomrule\n\\end{tabular}\n");
    write_if_changed(MATRIX_TEX, &cm)?;

    println!("gen: wrote {RS_OUT}, {PARAMS_TEX}, {MATRIX_TEX}");
    Ok(())
}

/// Strip LaTeX line comments (`%` to end of line, unless escaped as `\%`) so
/// commented-out `\req{...}` examples are not treated as real references.
fn strip_tex_comments(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    for line in s.lines() {
        let bytes = line.as_bytes();
        let mut cut = line.len();
        for i in 0..bytes.len() {
            if bytes[i] == b'%' && (i == 0 || bytes[i - 1] != b'\\') {
                cut = i;
                break;
            }
        }
        out.push_str(&line[..cut]);
        out.push('\n');
    }
    out
}

fn collect_files(root: &str, ext: &str, out: &mut Vec<PathBuf>) {
    let Ok(rd) = fs::read_dir(root) else { return };
    for entry in rd.flatten() {
        let p = entry.path();
        if p.is_dir() {
            if p.file_name().map(|n| n == "target").unwrap_or(false) {
                continue;
            }
            collect_files(&p.to_string_lossy(), ext, out);
        } else if p.extension().map(|e| e == ext).unwrap_or(false) {
            out.push(p);
        }
    }
}

fn lint() -> Result<(), Box<dyn Error>> {
    let reqs: Requirements = toml::from_str(&fs::read_to_string(REQS)?)?;
    let declared: BTreeSet<String> = reqs.requirement.iter().map(|r| r.id.clone()).collect();

    let id_re = Regex::new(r"\b(?:DEMI|ALG)-[A-Z0-9]+(?:-[A-Z0-9]+)*\b")?;
    let req_re = Regex::new(r"\\req\{([^}]+)\}")?;

    let mut refs_all: BTreeSet<String> = BTreeSet::new();
    let mut refs_tests: BTreeSet<String> = BTreeSet::new();

    let mut rs_files = Vec::new();
    for d in SCAN_RS_DIRS {
        collect_files(d, "rs", &mut rs_files);
    }
    for f in &rs_files {
        let txt = fs::read_to_string(f)?;
        let is_test = f.to_string_lossy().contains("/tests/") || txt.contains("#[test]");
        for m in id_re.find_iter(&txt) {
            let id = m.as_str().to_string();
            if is_test {
                refs_tests.insert(id.clone());
            }
            refs_all.insert(id);
        }
    }

    let mut tex_files = Vec::new();
    for d in SCAN_TEX_DIRS {
        collect_files(d, "tex", &mut tex_files);
    }
    for f in &tex_files {
        let txt = strip_tex_comments(&fs::read_to_string(f)?);
        for c in req_re.captures_iter(&txt) {
            refs_all.insert(c[1].to_string());
        }
    }

    let mut errors: Vec<String> = Vec::new();
    for r in refs_all.difference(&declared) {
        errors.push(format!(
            "reference to undeclared requirement `{r}` (add it to {REQS})"
        ));
    }
    for r in declared.difference(&refs_all) {
        errors.push(format!(
            "requirement `{r}` is declared but never referenced in spec or code"
        ));
    }
    for req in &reqs.requirement {
        if req.requires_test && !refs_tests.contains(&req.id) {
            errors.push(format!(
                "requirement `{}` has requires_test=true but no test references it",
                req.id
            ));
        }
    }

    if errors.is_empty() {
        let tested = reqs.requirement.iter().filter(|r| r.requires_test).count();
        println!(
            "lint: OK — {} requirements declared, all referenced; {tested} test-backed.",
            declared.len()
        );
        Ok(())
    } else {
        for e in &errors {
            eprintln!("  - {e}");
        }
        Err(format!("{} traceability error(s)", errors.len()).into())
    }
}
