// @generated by `cargo xtask gen` from design/demiurge.params.toml. DO NOT EDIT.
#![allow(dead_code)]

pub const CACHE_BLOCK_TOKENS: u64 = 256;
pub const CACHE_CHBL_LOAD_FACTOR_C: f64 = 1.25;
pub const CACHE_CUCKOO_MAX_LOADFACTOR: f64 = 0.9;
pub const CORRECTOR_ALPHA: f64 = 0.2;
pub const KV_ABANDONED_SESSION_TTL_S: u64 = 300;
pub const KV_FRAGMENTATION_SLACK: f64 = 0.05;
pub const KV_METADATA_OVERHEAD_FRACTION: f64 = 0.08;
pub const MIGRATION_ITL_BUDGET_FRACTION_EPS: f64 = 0.5;
pub const POOL_REBALANCE_COOLDOWN_S: u64 = 300;
pub const POOL_REBALANCE_HYSTERESIS: f64 = 0.1;
pub const POOL_WEIGHT_KV: f64 = 0.3;
pub const POOL_WEIGHT_QUEUE: f64 = 0.35;
pub const POOL_WEIGHT_SLO: f64 = 0.35;
pub const ROUTING_SHORT_CONTEXT_TOKENS: u64 = 512;
pub const ROUTING_SHORT_CONTEXT_WARMTH_OVERRIDE: f64 = 0.15;
pub const TELEMETRY_FRAME_RATE_HZ: u64 = 50;
pub const TELEMETRY_FREE_BLOCK_INTERRUPT_PCT: u64 = 20;
pub const TELEMETRY_GOSSIP_INTERVAL_MS: u64 = 100;
